/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperianceExperienceIdIndexRouteImport } from './routes/experiance.$experienceId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperianceExperienceIdIndexRoute =
  ExperianceExperienceIdIndexRouteImport.update({
    id: '/experiance/$experienceId/',
    path: '/experiance/$experienceId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiance/$experienceId': typeof ExperianceExperienceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiance/$experienceId': typeof ExperianceExperienceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiance/$experienceId/': typeof ExperianceExperienceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experiance/$experienceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiance/$experienceId'
  id: '__root__' | '/' | '/experiance/$experienceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperianceExperienceIdIndexRoute: typeof ExperianceExperienceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiance/$experienceId/': {
      id: '/experiance/$experienceId/'
      path: '/experiance/$experienceId'
      fullPath: '/experiance/$experienceId'
      preLoaderRoute: typeof ExperianceExperienceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperianceExperienceIdIndexRoute: ExperianceExperienceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
